# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Msk < Formula
  desc "Command your machines as one unified network"
  homepage "https://github.com/wisteriahuman/msk"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/msk/releases/download/v0.1.2/msk_Darwin_x86_64.tar.gz"
      sha256 "759c6f7ae6c06cb7b2a2e4e0ea2dff8229e15f75d819fc8065d18ef3f6cb7539"

      def install
        bin.install "msk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/msk/releases/download/v0.1.2/msk_Darwin_arm64.tar.gz"
      sha256 "4dc7d9167ae9a492a1253dc5e76ae7a6df0369ccb88a3d5702e6952e81e4f405"

      def install
        bin.install "msk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/msk/releases/download/v0.1.2/msk_Linux_x86_64.tar.gz"
      sha256 "9c374f887ea46a247a599a3f637f582e687fb2288bb97b247569f9e5cafbb6f4"
      def install
        bin.install "msk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/msk/releases/download/v0.1.2/msk_Linux_arm64.tar.gz"
      sha256 "cf2d6eae92f973e70fb425d9797455985e2aa6b3fdb231c4ed78360d540d8107"
      def install
        bin.install "msk"
      end
    end
  end
end
