# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prm < Formula
  desc "Markdownベースのノートアプリ Prometheus"
  homepage "https://github.com/wisteriahuman/Prometheus"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.0/Prometheus_Darwin_x86_64.tar.gz"
      sha256 "3fdd0d5b16d7106d86bdd10221f04aa294e8850b8bd887cd40f777e820947bb6"

      define_method(:install) do
        bin.install "prm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.0/Prometheus_Darwin_arm64.tar.gz"
      sha256 "a295040b8610fbf3c0b76429a6727799f9fa3664dd6ceb55d1462a5641866054"

      define_method(:install) do
        bin.install "prm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.0/Prometheus_Linux_x86_64.tar.gz"
      sha256 "3870ead15d38b523ecafc00fcdfa7276d3d56be26b59209c69498ec7d753071b"
      define_method(:install) do
        bin.install "prm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.0/Prometheus_Linux_arm64.tar.gz"
      sha256 "2859a2906476d96d4d60fd0f73f740e203777726f6ef2fb221cea502cac6ea13"
      define_method(:install) do
        bin.install "prm"
      end
    end
  end
end
