# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prm < Formula
  desc "Markdownベースのノートアプリ Prometheus"
  homepage "https://github.com/wisteriahuman/Prometheus"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.3/Prometheus_Darwin_x86_64.tar.gz"
      sha256 "cf9cb08fa5bccd78920948cd00d9f915731837387a2d3967a989a823236136ce"

      define_method(:install) do
        bin.install "prm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.3/Prometheus_Darwin_arm64.tar.gz"
      sha256 "1de2ea5e79c5c47b0f36f5f409f3fc9d405f0fd91126a67dba227edddb3bb27a"

      define_method(:install) do
        bin.install "prm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.3/Prometheus_Linux_x86_64.tar.gz"
      sha256 "b6b1f338f185598bc5c328ed5e02b1ce38f49cf06c89ff34822a7091dd7a2b1e"
      define_method(:install) do
        bin.install "prm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.4.3/Prometheus_Linux_arm64.tar.gz"
      sha256 "4bc732a6f5f58a998cbb481279b62bfa457d4a4135cbb2e17e90c1d4203bb3ae"
      define_method(:install) do
        bin.install "prm"
      end
    end
  end
end
