# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prometheus < Formula
  desc "Markdownベースのノートアプリ"
  homepage "https://github.com/wisteriahuman/Prometheus"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.1.0/Prometheus_Darwin_x86_64.tar.gz"
      sha256 "5b5598d588e136a7377168bbaa6278075fb70f83342c9eaed39190072d25641a"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.1.0/Prometheus_Darwin_arm64.tar.gz"
      sha256 "5e83c1379562c1b9a739a2d102f41ea5a35a295ead81737df420961a0e05e805"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.1.0/Prometheus_Linux_x86_64.tar.gz"
      sha256 "bb876bcb508981e49345dbd665488e01e347a6636585fd6d7ce22558a364daf8"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.1.0/Prometheus_Linux_arm64.tar.gz"
      sha256 "926aff4f05bda996a07eec4ef37792cb8fb899c5d2eab9c81aea08a31d06fab0"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end
end
