# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prometheus < Formula
  desc "Markdownベースのノートアプリ"
  homepage "https://github.com/wisteriahuman/Prometheus"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.2.1/Prometheus_Darwin_x86_64.tar.gz"
      sha256 "8aa61fc699395563f325765fed989537a2985472feeb7141f5fbda8b4cbd6100"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.2.1/Prometheus_Darwin_arm64.tar.gz"
      sha256 "9dd151c655df44ae698686d20b2cb60f6c59d6d714a83ec7f466c2dcdc030097"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.2.1/Prometheus_Linux_x86_64.tar.gz"
      sha256 "2daab33373651e1d30a3f5bf880b100282fded90aa8480ccc8fa9ef767a1b83b"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.2.1/Prometheus_Linux_arm64.tar.gz"
      sha256 "d88e905595949e91ca6357fb839caa551724cfc17d99fa8eb8169e8cf10aafff"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end
end
