# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prometheus < Formula
  desc "Markdownベースのノートアプリ"
  homepage "https://github.com/wisteriahuman/Prometheus"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.3.0/Prometheus_Darwin_x86_64.tar.gz"
      sha256 "fd3279532606e58b6a8fd0141b5f44d419fe9cedc8f0aa71fae2a71c0fd07e47"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.3.0/Prometheus_Darwin_arm64.tar.gz"
      sha256 "61ce5ad50736a0047fd0f31e63fee8bbda9a66e6eb81f006307a939bc7752f66"

      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.3.0/Prometheus_Linux_x86_64.tar.gz"
      sha256 "e7fb87ded8260a6c77636ea9c53cf6099c7791bc10f2b1fe84e0f26239f1a396"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/Prometheus/releases/download/v0.3.0/Prometheus_Linux_arm64.tar.gz"
      sha256 "4cfe85f0a7ff67bfe6f3771ef8f022064f17171a1736ef791ac39eefdd101e87"
      define_method(:install) do
        bin.install "prometheus"
      end
    end
  end
end
