# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoCli < Formula
  desc "CLI Todoアプリ"
  homepage "https://github.com/wisteriahuman/todo-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.2/todo-cli_Darwin_x86_64.tar.gz"
      sha256 "32cd94c2f09ad8903069f25109cac360991372e19acc6461faa9fa10bf1372f9"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.2/todo-cli_Darwin_arm64.tar.gz"
      sha256 "f3763b21e1f712025d9f9d2c19142f0da4ee9e14eac137420961ab96f77ba561"

      def install
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.2/todo-cli_Linux_x86_64.tar.gz"
      sha256 "6f2b290707f9bc84ada061e50bc081dc98b288beb71439e210d59acca042ebb4"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.2/todo-cli_Linux_arm64.tar.gz"
      sha256 "c5f145dc1b2cab6f826879c0b7b8b0b2927d60d5b1a8ad92543a5f304000c90a"
      def install
        bin.install "todo"
      end
    end
  end
end
