# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoCli < Formula
  desc "CLI Todoアプリ"
  homepage "https://github.com/wisteriahuman/todo-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.1/todo-cli_Darwin_x86_64.tar.gz"
      sha256 "d3f6c9516f66139dd6ff7576bd7a24a33e3bbd5ee142b3d94ccb7163eedda310"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.1/todo-cli_Darwin_arm64.tar.gz"
      sha256 "2d18e61d9e9d3641db20dfe0af258f1ae6d5698c0b4b09fafd7fc90d596ff71b"

      def install
        bin.install "todo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.1/todo-cli_Linux_x86_64.tar.gz"
      sha256 "0e2d04aed5bd3cbb1dac0bbfb401c8fbe8c31967934d07a9da15caf2268976de"
      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wisteriahuman/todo-cli/releases/download/v0.1.1/todo-cli_Linux_arm64.tar.gz"
      sha256 "cd7b4a6973a018775cb61cbb12f2addd6d68f889222f37d639a7c2fd92a7d52c"
      def install
        bin.install "todo"
      end
    end
  end
end
